spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 15wHnKxZPKe6qpn6KYaHYqHjAvAICSwP
            client-secret: a5a11734-c7ed-4a59-a213-71b7ff3f9f1d
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-5dwg5a6hii5h5t20.us.auth0.com/