version: "4.12"
services:
  apache:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
    command: sh -c "composer install && php artisan serve --host 0.0.0.0"
    ports:
      - 8000:8000
    expose:
      - 8000
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - ./laravel:/home/laravel
