version: "4.12"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Pe6mdBg2ILYQDICuN3gGqUR4AHAa4BW9KPSfD7YnFzUmamJY
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: Pe6mdBg2ILYQDICuN3gGqUR4AHAa4BW9KPSfD7YnFzUmamJY
    ports:
      - "3306:3306"
    expose:
      - 3306

  apache:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
    command: sh -c "composer install && php artisan serve --host 0.0.0.0"
    ports:
      - 80:8000
    expose:
      - 80
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - ./laravel:/home/laravel
